name: Build release binary

env:
  RUST_BACKTRACE: 1
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build on ${{ matrix.build }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build: [linux-amd64, macos-x86_64, macos-aarch64] #, linux-aarch64, macos-arm64]
        include:
          - build: linux-amd64
            os: ubuntu-latest
            rust: stable
            artifact_name: 'gerb-linux-amd64'
            target: x86_64-unknown-linux-gnu
          - build: macos-x86_64
            os: macos-latest
            rust: stable
            target: x86_64-apple-darwin
            artifact_name: 'gerb-darwin-amd64'
         #- build: linux-aarch64
         #  os: ubuntu-latest
         #  rust: stable
         #  target: aarch64-unknown-linux-gnu
         #  artifact_name: 'gerb-linux-aarch64'
         #- build: macos-arm64
         #  os: macos-latest
         #  rust: stable
         #  target: aarch64-apple-darwin
         #  artifact_name: 'gerb-darwin-arm64'
          - build: macos-aarch64
            os: ubuntu-latest
            rust: stable
            artifact_name: 'gerb-darwin-aarch64'
            target: aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v2
      - id: cache-rustup
        name: Cache Rust toolchain
        uses: actions/cache@v3
        with:
          path: ~/.rustup
          key: toolchain-${{ matrix.os }}-${{ matrix.rust }}
      - if: ${{ steps.cache-rustup.outputs.cache-hit != 'true' }}
        name: Install Rust ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
      - name: Configure cargo data directory
        # After this point, all cargo registry and crate data is stored in
        # $GITHUB_WORKSPACE/.cargo_home. This allows us to cache only the files
        # that are needed during the build process. Additionally, this works
        # around a bug in the 'cache' action that causes directories outside of
        # the workspace dir to be saved/restored incorrectly.
        run: echo "CARGO_HOME=$(pwd)/.cargo_home" >> $GITHUB_ENV
      - id: cache-cargo
        name: Cache cargo configuration and installations
        uses: actions/cache@v3
        with:
          path: ${{ env.CARGO_HOME }}
          key: cargo-${{ matrix.os }}-${{ matrix.rust }}
      - if: ${{ steps.cache-cargo.outputs.cache-hit != 'true' }} && matrix.target
        name: Setup Rust target
        run: |
          mkdir -p "${{ env.CARGO_HOME }}"
          cat << EOF > "${{ env.CARGO_HOME }}"/config.toml
          [build]
          target = "${{ matrix.target }}"
          EOF
      - name: Install dependencies (macos x86_64)
        if: matrix.os == 'macos-latest' && matrix.target == 'x86_64-apple-darwin'
        shell: bash
        run: |
          set -ex
          brew install librsvg gtk+3 gnome-icon-theme
      - name: Install dependencies (linux)
        if: matrix.os == 'ubuntu-latest' && matrix.target == 'x86_64-unknown-linux-gnu'
        run: |
          set -ex
          sudo apt install libgtk-3-dev
          cargo install cargo-deb
      - name: Build binary
        if: matrix.target != 'aarch64-apple-darwin'
        run: |
          cargo build --release
          mv target/*/release/gerb target/gerb || true
          mv target/release/gerb target/gerb || true
      - name: Build m1 binary
        if: matrix.target == 'aarch64-apple-darwin'
        run: |
          sudo apt install python3-pip
          pip install cargo-zigbuild
          docker run --rm -v $(pwd):/io -w /io messense/cargo-zigbuild cargo zigbuild --release --target aarch64-apple-darwin
          ls target/ || true
          ls target/aa*/ || true
          mv target/*/release/gerb target/gerb || true
          mv target/release/gerb target/gerb || true
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact_name }}
          path: target/gerb
          if-no-files-found: error
          retention-days: 30
      - name: Build deb package
        if: matrix.os == 'ubuntu-latest' && matrix.target == 'x86_64-unknown-linux-gnu'
        shell: bash
        run: |
          cargo deb --target=${{ matrix.target }}
      - name: Upload Artifacts
        if: matrix.os == 'ubuntu-latest' && matrix.target == 'x86_64-unknown-linux-gnu'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target }}-deb
          path: target/${{ matrix.target }}/debian/*.deb
          if-no-files-found: error
          retention-days: 30
