name: Spellcheck Markdown files

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths:
      - '*.md'

jobs:
  test:
    name: Test on ${{ matrix.build }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build: [linux-amd64]
        include:
          - build: linux-amd64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v2
      - name: Install aspell
        run: |
          set -ex
          sudo apt install aspell aspell-en
      - name: Run aspell
        shell: bash
        run: |
          bash .github/spellcheck.sh 
